### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by fcamuc** [Leone25/kitaboo-downloader#1]
![Screenshot from 2021-09-16 17-53-55](https://user-images.githubusercontent.com/65353822/133644945-aa227f17-44c9-4e32-b57c-1a0e6e110d60.png)

Se provo a scaricare un libro mi da questo errore:
```

/home/fcamuc/tool-libri/kitaboo-downloader/index.js:25
        console.log(spawnSync(inkscapePath, [`--export-filename=page${('0000'+i).slice(-4)}.pdf`, 'page'+('0000'+i).slice(-4)+'.svg'], {cwd: __dirname+"/temp/"}).stderr.toString());
                                                                                                                                                                        ^

TypeError: Cannot read properties of null (reading 'toString')
    at /home/fcamuc/tool-libri/kitaboo-downloader/index.js:25:169

```

non me ne intendo di JavaScript, sai aiutarmi?

**Comment by Leone25** [comment]
Domanda 1. Hai inkscape installato e hai cambiato il path dell'eseguibile?

(Lo script è stato fatto in windows quindi inevitabilmente il path dell'eseguibile è diverso)

**Comment by fcamuc** [comment]
Ah mi ero dimenticato di cambiare la path dell'eseguibile. 
Cambiandolo mi dice che l'argument " --export-filename " non esiste, perchè su linux per esportare i pdf vuole " --export-pdf= ".

Sostituendo questo valore il tool funziona

**Comment by Leone25** [comment]
Buono a sapersi, grazie mille

**Comment by fcamuc** [comment]
Grazie a te, i tuoi tool per scaricare i libri sono la mia salvezza, le app degli editori sono inutilizzabili
