### ISSUE TITLE
Doesn't work with https://webreader.zanichelli.it/6.0

### ISSUE THREAD

**Issue by pietroMastro92** [Leone25/kitaboo-downloader#10]
The downloader return "invalid url" message if used on the latest version of https://webreader.zanichelli.it/6.0

**Comment by Leone25** [comment]
Ty for letting me know,

to put it simply they are assholes, they know about me so they are trying their best to stop me, this time it was as simple as just adding an `#` to the url that breaks the url parser, easy enough to fix.

I've now updated the code so if you download it again it should work now

**Comment by pietroMastro92** [comment]
Thanks
