### ISSUE TITLE
Errore "Invalid URL"

### ISSUE THREAD

**Issue by AmilyHope** [Leone25/kitaboo-downloader#13]
Ciao ho provato a scaricare un libro seguendo passo passo la guida, ma quando incollo il link sul terminale riscontro questo errore: "Invalid URL" .
questo è lo screen da dove recupero il link da copiare sul sito zanichelli
![image](https://user-images.githubusercontent.com/117513900/221178034-83b3a31f-b7db-4d59-88f6-c6a6208ab68c.png)
questo è lo screen dell'errore:
![image](https://user-images.githubusercontent.com/117513900/221178578-8a2b82a3-d54a-4b28-979a-52069d587e8b.png)

Potresti cortesemente aiutarmi dicendomi come risolvere il problema e scaricare i libri?
Ti ringrazio

**Comment by Leone25** [comment]
strano, perchè io ho lo stesso libro e funziona

potresti provare ad inserire a riga 32 dell'`index.js` `console.log(redirectUrl, bookId, usertoken)`, salva, riprova poi ad eseguire lo script e mostrami il risultato.

**Comment by AmilyHope** [comment]
Ciao ho fatto questa modifica:
prima era così: 
![image](https://user-images.githubusercontent.com/117513900/221222705-d79d85ac-edc5-477e-9c47-c17d9d376a46.png)
l'ho poi modificato così:
![image](https://user-images.githubusercontent.com/117513900/221222982-82db710a-e537-4bf9-9b6b-1364c702661b.png) e adesso mi compare questo:
![image](https://user-images.githubusercontent.com/117513900/221223728-67c5cbbb-8ac1-409a-9328-9798144e3f0b.png)

grazie

**Comment by Leone25** [comment]
mi sa che tu hai scaricato una versione diversa/vecchia del codice perchè riga 22 è diversa ed è per questo che hai problemi, dovrebbe essere `if (res.status == 302) return new URL(res.headers.get("location").replace('#', ''));`, ma la tua è `if (res.status == 302) return new URL(res.headers.get("location"));`

**Comment by AmilyHope** [comment]
Ciao, mi sa di si, avevo la versione vecchia, perchè dopo aver scaricato la nuova adesso va. quindi grazie mille!!!!
Una domanda: invece per scaricare un libro che ha tale link:
https://web-booktab.zanichelli.it/?idOpera=06A37C6FA0BF29CEC1257D26002DB730 
devo necessariamente usare la guida per booktab-downloader ?
la stavo seguendo e sono arrivata al rigo
Click on the cover of the volume you'd like to download in the booktab page 
sono arrivata qui:
![image](https://user-images.githubusercontent.com/117513900/221276801-c8411424-9199-4b43-b605-56204043fb8e.png)
sono bloccata dove dice
Back in the network tools look for the volume.xml or spine.xml file that should appear in the network tab
Select it and scroll down to the boottom of the headers where it says Cookie
If you're on macOS: paste the cookie in the cookies.txt file, otherwise copy all the cookies (do not include the Cookie: part) and paste them in the terminal and press enter
Take the ISBN of the book you'd like to download, paste it into the terminal and press enter

perdonami ma non ho capito cosa devo fare per andare avanti.

**Comment by Leone25** [comment]
Devi aprire gli strumenti da sviluppatore prima, si fa con f12

**Comment by AmilyHope** [comment]
si fino a lì ci sono arrivata
![image](https://user-images.githubusercontent.com/117513900/221295220-ef9034b5-4658-49dc-b851-e27debea745c.png)
mi aspettavo di trovare  i file the volume.xml spine.xml nel tab rete ma non lo trovo

**Comment by Leone25** [comment]
Devi ricaricare la pagina dopo che hai aperto gli strumenti da sviluppatore

**Comment by AmilyHope** [comment]
ciao ci ho provato, da qui era così:
![image](https://user-images.githubusercontent.com/117513900/221372508-5345faa1-61a3-4dc0-af4e-3a10086fb7aa.png)
ho poi ricaricato (cliccando la freccia rotonda in alto a sinistra  vicino all'url)  e mi esce così:
![image](https://user-images.githubusercontent.com/117513900/221372536-7f162cfb-af41-4af8-8eca-14fa009251f5.png)
potresti cortesemente dirmi ciò che mi dovrei aspettare di vedere e spiegarmi tutti i passaggi da fare, fino ad arrivare al download? almeno evito di disturbarti ancora ;)
grazie mille infinite

**Comment by Leone25** [comment]
Hai qualcosa nel campo di ricerca che sta a sinistra dell'opzione inverti, cancella quella roba li, dovrebbe comparire

**Comment by AmilyHope** [comment]
ciao, sono riuscita ad arrivare nella sezione cookie del file spine.xml come qui:
![image](https://user-images.githubusercontent.com/117513900/221399254-5f268d52-7c0a-4170-8c03-b127fbd26496.png)
adesso sulla guida c'è scritto che devo copiare tutti i cookie e incollarli  del terminale, ma come faccio a copiarli tutti? incollarne uno alla volta o tutti insieme? quale campo? nome, valore? c'è una combinazione di tasti del testo specifico per copiarli e incollarli nel terminale?
seguendo la guida nel terminale mi trovo così:
![image](https://user-images.githubusercontent.com/117513900/221399369-6ac277bf-0fb3-417b-84d4-b8a065525df6.png)
potresti cortesemente dirmi come fare, se possibile, in modo dettagliato. grazie

**Comment by Leone25** [comment]
Al posto di andare sulla schermata dedicata dei cookie, vai sulla schermata "informazioni", scorri in basso e dovrebbe dire cookie, è la roba che sta li a fianco che devi copiare
