### ISSUE TITLE
New link

### ISSUE THREAD

**Issue by teo2600** [Leone25/kitaboo-downloader#14]
Mi pare di capire che Zanichelli ha appena modificato la codifica del link, ora è:

https://webmy.zanichelli.it/ebook/XXXXXXXXXXXXX?origPlatform=https://my.zanichelli.it&origSection=bookmarks&_gl=1*1mehjuz*_ga*NjM5NzczNDA1LjE2ODEzNzE3MTI.*_ga_FL8QBN8HHQ*MTY4MTQ5MzU0MS43LjEuMTY4MTQ5Njk3MS4wLjAuMA..

Questa diventa la nuova interfaccia web di lettura:

https://webreader.zanichelli.it/6.0/zanichelli/#/reader?mode=online

E le (immagini delle) pagine mi sembrano queste:

https://.../page0010.svgz

**Comment by Leone25** [comment]
per i libri che ho a disposizione io, mi sembra ancora il vecchio...

**Comment by teo2600** [comment]
I miei sono cambiati tutti in questi giorni...

**Comment by Leone25** [comment]
Ma lo stesso libro prima aveva un altro link?

**Comment by teo2600** [comment]
Sì, e infatti lo script funzionava benissimo. Ora non più, purtroppo...

**Comment by Gioele-97** [comment]
Ho lo stesso problema!

**Comment by Leone25** [comment]
ho provveduto ad aggiornare e fornire nuove istruzioni per l'uso
