### ISSUE TITLE
Invalid Url

### ISSUE THREAD

**Issue by NakamotoShigetoki** [Leone25/kitaboo-downloader#15]
Sembra che Zanichelli abbia refactorato il link dei libri Kitaboo, infatti sono composti nella seguente maniera:
https://webmy.zanichelli.it/ebook/IDQUALCOSA?origPlatform=https://my.zanichelli.it&origSection=purchases
Dove IDQUALCOSA e' un codice numerico di 13 cifre. Prima era tipo:
https://my.zanichelli.it/kitaboo/IDQUALCOSA

Sembra che non ci sia modo di far funzionare lo script anche dando userToken e bookId, la richiesta a riga 50 da un Error 500.

**Comment by Leone25** [comment]
ho provveduto ad aggiornare e fornire nuove istruzioni per l'uso
