### ISSUE TITLE
UnhandledPromiseRejectionWarning non appena viene inserito il cookie

### ISSUE THREAD

**Issue by 1alessandro1** [Leone25/kitaboo-downloader#17]
Ciao, 

Ho seguito la guida per ottenere l'eBookID, ho incollato (mettendo prima la spunta su "Raw") tutto il campo del valore dopo `"Cookie; "` e sembra che non abbia dato errori questa parte di login, poiché vedo che inizia con:

```
Processing...
Downloading page0001

```

Ma appena dopo:

```
Processing...
Downloading page0001
(node:6540) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at /home/ale/Documents/kitaboo-downloader/index.js:47:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

modi per sistemare?

Sembra che il file venga anche scritto, ma solo 15Bytes:

![image](https://user-images.githubusercontent.com/46293832/232856512-f6af2d00-933c-43cf-a014-6785742976d5.png)

**Comment by Leone25** [comment]
L'errore è generalmente causato da una versione troppo vecchia di node.js

Che versione hai? `node -v`

Puoi provare ad aggiornare?

**Comment by 1alessandro1** [comment]
`v12.22.12`

**Comment by Leone25** [comment]
si, decisamente troppo vecchia, prova ad aggiornare

**Comment by 1alessandro1** [comment]
Cambiando la versione di node (su macOS)

```
╰─❯ node -v
v19.9.0

```

![image](https://user-images.githubusercontent.com/46293832/232859117-21ce7122-def4-4b94-b605-e0cf944f6572.png)

**Comment by 1alessandro1** [comment]
L'output è un PDF vuoto di 430 pagine

**Comment by Leone25** [comment]
no, generalmente quell'errore è causato da un errore nel cookie, ti sei ricordato di mostrare gli header raw?

**Comment by 1alessandro1** [comment]
Si, ho la richiesta GET completa 

![image](https://user-images.githubusercontent.com/46293832/232861441-8be07afd-9beb-4500-998d-9035054f98fb.png)

**Comment by Leone25** [comment]
aspe, hai detto che stai usando macos? mi pare che ci siano problemi su macos a causa della libreria che uso per l'input

prova perfavore ad eseguire lo script così `node index.js 2203355 "<your-cookie>"`, le virgolette devono rimanere

**Comment by 1alessandro1** [comment]
macOS mi serviva per avere una versione di node più recente, ho provato il tuo comando:

![image](https://user-images.githubusercontent.com/46293832/232862908-cdd5375f-8b50-4fdb-b2e7-390a034500ba.png)

Hai telegram? Se vuoi ti giro il cookie

**Comment by Leone25** [comment]
riprova perfavore eliminando la parte dopo l'ultimo `;` del cookie (mantieni comunque il `"` finale)

**Comment by 1alessandro1** [comment]
Ho riprovato, mi da un altro errore ora:

![image](https://user-images.githubusercontent.com/46293832/232910733-07c379e3-a792-4b0e-b409-000520b14fb2.png)

**Comment by Leone25** [comment]
hmmm, puoi provare ad inserire `console.log(svg);` dopo linea 56 e provare di nuovo?

**Comment by 1alessandro1** [comment]
![image](https://user-images.githubusercontent.com/46293832/233011749-0ff8ba26-5649-40de-bc6b-ece8292ca260.png)

AccessDenied

![image](https://user-images.githubusercontent.com/46293832/233012550-d5604966-47fd-4252-9ac5-2901f5919d50.png)

**Comment by Leone25** [comment]
scrivimi in privato su twitter (stesso nome +03)
