### ISSUE TITLE
LaZ ebook reader

### ISSUE THREAD

**Issue by ghost** [Leone25/kitaboo-downloader#18]

**Comment by Leone25** [comment]
questo script?

devo ammettere che non comprendo a pieno la domanda...

**Comment by aniccolai** [comment]
Alcuni Libri adesso non spuntano più su booktab web , ma hanno inserito un nuovo reader che si chiama LaZ Ebook . Quindi lo script non si può usare più... mi chiedevo se si poteva trovare una nuova soluzione :(

**Comment by Leone25** [comment]
LaZ === kitaboo

booktab web === booktab web
