### ISSUE TITLE
Mi esce un errore

### ISSUE THREAD

**Issue by Mario03482** [Leone25/kitaboo-downloader#19]
TypeError: Cannot read properties of undefined (reading 'metadata')
    at C:\Users\Hp\Desktop\test\kitaboo-downloader-main\index.js:32:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by Leone25** [comment]
potresti aggiungere a linea 31 `console.log(content);` e rieseguire lo script?

**Comment by Mario03482** [comment]
Lo aggiungo a index.js?

**Comment by Mario03482** [comment]
Processing...

{
  Error: {
    Code: [ 'MissingKey' ],
    Message: [ 'Missing Key-Pair-Id query parameter or cookie value' ]
  }
}
C:\Users\Hp\Desktop\test\kitaboo-downloader-main\index.js:32
        let title = content.package.metadata[0]["dc:title"][0];
                                    ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at C:\Users\Hp\Desktop\test\kitaboo-downloader-main\index.js:32:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by Mario03482** [comment]
Ci sono riuscito. Avevo dimenticato di mettere Raw per visualizzare il cookie

**Comment by ValeDeFra27** [comment]
![image](https://github.com/Leone25/kitaboo-downloader/assets/138681357/155c061e-659a-4e86-91e2-a6f17b5099ab)

Anche a me da questo errore eppure la RAW è attiva
