### ISSUE TITLE
Need help with the code

### ISSUE THREAD

**Issue by Francesco-Avagliano** [Leone25/kitaboo-downloader#2]
Hi! Thank you for providing your other work as well.

I'm having trouble in understanding what datas I should copy and paste into the "Input the cookies headers" in the terminal
<img width="1459" alt="Screenshot 2021-10-06 at 20 56 51" src="https://user-images.githubusercontent.com/78238206/136265966-7caf2e7b-2ec6-48cf-971a-db2f2d754f71.png">

**Comment by Francesco-Avagliano** [comment]
If I copy and paste every code of the terminal I get this error repetead a lot of times: UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi(node:21351)

**Comment by Leone25** [comment]
That us caused by caching, for whatever reason chromium some times doesn't listen to the disable caching setting

Please use firefox . . . 🙄
