### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by piumalinux** [Leone25/kitaboo-downloader#21]
Is there a Linux Version of this? Thanx a lot for your work.

**Comment by piumalinux** [comment]
OK, su Linux ho seguito le istruzioni date per Windows con nodejs. Ha scaricato 840 pagine ma alla fine restituisce questo errore:
`/home/tommaso/Scrivania/kitaboo-downloader-main/node_modules/node-fetch/lib/index.js:1505
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://webreader.zanichelli.it/506594/html5/506594/OPS/images/page0841.svgz failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/tommaso/Scrivania/kitaboo-downloader-main/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
`

**Comment by Leone25** [comment]
quello significa ce ti è morto internet

funziona senza problemi su linux, l'ho usato su linux anch'io

**Comment by piumalinux** [comment]
Sì hai ragione! Infatti forse bittorrent stava usando troppa banda. Ritentando ha funzionato alla grande. Mi chiedevo se funzionasse anche nella versione "lettura immersiva" in modo da avere un pdf navigabile, ma mi ha dato questo:
`/home/tommaso/Scrivania/kitaboo-downloader-main/index.js:32
	let title = content.package.metadata[0]["dc:title"][0];
	                            ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at /home/tommaso/Scrivania/kitaboo-downloader-main/index.js:32:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.0
`

**Comment by Leone25** [comment]
purtroppo quello è un po' un casino da gestire perchè di per se la zanichelli offre i libri come immagini + ci sono delle pagine html che contengono le parole, però unirle è difficile e quindi questo programma si limita solo ad estrarre le immagini

**Comment by agreselin** [comment]
Confermo che funziona su Fedora 38. Grazie @Leone25 :-)

Per riavere il testo cercabile ho provato `ocrmypdf`:
```
sudo dnf install ocrmypdf tesseract-langpack-ita
ocrmypdf -l ita --output-type pdf INPUT.pdf OUTPUT.pdf
```
(per un libro in italiano.) Non ho controllato tanto ma mi pare che abbia funzionato bene.

Sapresti fargli integrare il sommario nel PDF?
