### ISSUE TITLE
Nuovo ebook reader(?)

### ISSUE THREAD

**Issue by LeiX-21** [Leone25/kitaboo-downloader#22]
Ciao, di recente è spuntato il nuovo https://webreader.zanichelli.it/ , sapete come estrarre pdf dai libri che si leggono da qui? Mi sembra che tutti quelli che prima funzionavano tramite kitaboo reader ora girano tutti su questo nuovo e-reader. Sapete come procedere, se si può, in questi casi?

**Comment by Leone25** [comment]
per quanto ne sappia io dovrebbe ancora funzionare tutto

purtroppo non ho più libri che si aprono con kitaboo/webreader quindi non posso provare

**Comment by LeiX-21** [comment]
Lo script in sè funziona anche, ma non riesco a recuperare i cookie, non mi esce più la scritta "Cookie:" come una volta e sono sempre nella schermata "Network"

**Comment by LeiX-21** [comment]
Ok, no, mi scuso, stavo sbagliando procedura per recuperare il cookie, durante l'estrazione però ricevo questo messaggio
è normale?
![image](https://github.com/Leone25/kitaboo-downloader/assets/67823089/d13210af-9182-4976-a690-3f9e59646ece)

**Comment by Leone25** [comment]
Buon giorno, ho ricevuto vari messaggi da molteplici persone che hanno riscontrato questo problema, ciò è dovuto ad un recente aggiornamento del sito che cripta tutte le pagine dei libri. Ho dato un rapido sguardo ed attualmente non mi sembra troppo chiaro come il tutto funzioni quindi un aggiornamento richiederà del tempo. Sono comunque aperto a contributi da parte di terzi.

**Comment by MatHeartGaming** [comment]
Quindi, siccome le pagine dei libri sono ora criptate, non è più possibile usare lo script per scaricare i libri?

**Comment by Leone25** [comment]
fatto un aggiornamento da poco che dovrebbe risolvere il problema
