### ISSUE TITLE
Prompt-sync input repeats itself in terminal 

### ISSUE THREAD

**Issue by RiccardoWilliam** [Leone25/kitaboo-downloader#23]
Ciao, ho provato a usare lo script seguendo la guida ma quando si deve incollare l'intero testo del cookie questo viene duplicato molte volte nel terminale prima che io prema invio, ho cercato online e a quanto pare prompt-sync non accetta bene input troppo lunghi. Dovrei usare solo una parte dei valori del cookie oppure è bug dovuto a prompt-sync?

**Comment by Leone25** [comment]
fregatene, è solo un bug "estetico" se premi invio dovrebbe funzionare tutto (potrebbero esserci problemi con macos da quanto mi riferiscono, ma dettagli...)
