### ISSUE TITLE
Errore dopo aver inserito il cookie

### ISSUE THREAD

**Issue by OnePewPew** [Leone25/kitaboo-downloader#24]
dopo aver inserito il cookie, il programma invia un messaggio d'errore:

[percorso del programma]\index.js:32
let title = content.package.metadata[0]["dc:title"][0];
                               
TypeError: Cannot read properties of undefined (reading 'metadata') 
    at [percorso del programma]\index.js:32:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
![image](https://github.com/Leone25/kitaboo-downloader/assets/73146958/71669488-c35e-4a25-a65c-e38671cef41b)

**Comment by Leone25** [comment]
hmmm generalmente quell'errore significa che o hai inserito male il cookie, o hai inserito male l'id del  libro, altrimenti su linea 29 prova ad inserire `console.log(content);` e fammi sapere cosa ti dice

**Comment by OnePewPew** [comment]
Allora, nonostante abbia controllato le istruzioni nuovamente mi sembra che le abbia seguite correttamente e ho anche riprovato con un altro libro senza aver successo. In ogni caso, ho inserito `console.log(content);` alla fine del cookie e risulta questo
![image](https://github.com/Leone25/kitaboo-downloader/assets/73146958/5b1e3bb4-079e-44f0-a53a-6632d406c8f3)

Dopo `TypeError:` ci sarebbe il cookie che ho copiato da content.opf e in caso servisse per risolvere il problema, lo mostrerei senza problemi.
Ho notato che incollando il cookie dopo averlo copiato dalla scheda network è duplicato molteplici volte e inoltre è stato aperto anche un issue dedicato. Potrebbe essere questo il problema?

**Comment by Leone25** [comment]
no, il cookie copiato varie volte è normale
si, mi servirebbe vedere le righe obfuscate

**Comment by Leone25** [comment]
ah ok, mi sono spiegato male, il `console.log(content);` va aggiunto al `index.js` a riga 29, non al cookie, devi proprio modificare il codice.

**Comment by OnePewPew** [comment]
Va bene, ho inserito tutto il necessario e questo è ciò che appare:
![image](https://github.com/Leone25/kitaboo-downloader/assets/73146958/9afac115-6c36-4614-98a3-74d331a9b070)

**Comment by Leone25** [comment]
Ah ok ho appena visto l'errore, se stai attento dentro al cookie c'è un punto dove ci sono "...", quello significa che il cookie è stato abbreviato, devi abilitare raw e riprovare.

Purtroppo però lo script non funzionerà perché hanno appena fatto un aggiornamento a booktab e adesso tutte le pagine sono cryptate, sto lavorando ad un fix, ma ci vorra un po'

**Comment by Leone25** [comment]
Buone notizie!
Tutto fixato, ci sono nuove istruzioni, perfavore seguitele attentamente e scaricate tutto da 0.
Buon apprendimento!

**Comment by OnePewPew** [comment]
Benissimo, grazie mille!
