### ISSUE TITLE
Problema in fase di download 

### ISSUE THREAD

**Issue by gab-viar** [Leone25/kitaboo-downloader#25]
Ciao, devo scaricare tre libro ed il primo tutto liscio gli altri due dopo aver inserito i cookie e iniziato il download appare la scritta: parseXml: data after document end has been discared. SVGtoPDF: the input does not look like a valid SVG, facendo il download correttamente ma il pdf risulta completamente vuoto. Grazie in anitcipo

**Comment by LeiX-21** [comment]
> Ciao, devo scaricare tre libro ed il primo tutto liscio gli altri due dopo aver inserito i cookie e iniziato il download appare la scritta: parseXml: data after document end has been discared. SVGtoPDF: the input does not look like a valid SVG, facendo il download correttamente ma il pdf risulta completamente vuoto. Grazie in anitcipo

Ho lo stesso problema anche io

**Comment by Leone25** [comment]
Buon giorno, ho ricevuto vari messaggi da molteplici persone che hanno riscontrato questo problema, ciò è dovuto ad un recente aggiornamento del sito che cripta tutte le pagine dei libri. Ho dato un rapido sguardo ed attualmente non mi sembra troppo chiaro come il tutto funzioni quindi un aggiornamento richiederà del tempo. Sono comunque aperto a contributi da parte di terzi.

**Comment by ninnoh** [comment]
> Buon giorno, ho ricevuto vari messaggi da molteplici persone che hanno riscontrato questo problema, ciò è dovuto ad un recente aggiornamento del sito che cripta tutte le pagine dei libri. Ho dato un rapido sguardo ed attualmente non mi sembra troppo chiaro come il tutto funzioni quindi un aggiornamento richiederà del tempo. Sono comunque aperto a contributi da parte di terzi.

Non so se possa servire, ma in alcun caso allego qualcosa che ho visto:

In ispeziona elemento c'e' una richiesta a https://webreader.zanichelli.it/downloadapi/auth/contentserver/book/XXX/FIXED_EPUB_IMAGE/XXX/downloadBook?state=online
che restituisce 
{
    "responseCode": 200,
    "responseMsg": "URL_FILE",
    "content_ownership": "TRUE",
    "privateKey": "MIICdwIBADANBgkqhkiG9w0BAQEF...",
    "lastPageFolio": "",
    "isbn": "...",
    "clientBookId": "...",
    "jwtToken": "..."
}

mi tocca comprendere ora come decryptare i file.
Noto anche richieste a 
https://webreader.zanichelli.it/BOOKID/html5/BOOKID/OPS/enc.key
e
https://webreader.zanichelli.it/BOOKID/html5/BOOKID/OPS/enc_resource.key
credo che molto probabilmente le chiavi siano dalle ultime due url

**Comment by Leone25** [comment]
Buone notizie!
Tutto fixato, ci sono nuove istruzioni, perfavore seguitele attentamente e scaricate tutto da 0.
Buon apprendimento!

**Comment by almi05** [comment]
> Buone notizie! Tutto fixato, ci sono nuove istruzioni, perfavore seguitele attentamente e scaricate tutto da 0. Buon apprendimento!

manca solo il comando di avvio dello script 😅

**Comment by GioIacca9** [comment]
Ho provato il nuovo metodo ma mettendo nel sito per l'RSA la chiave e il testo da decifrare, ricevo l'errore "Data must not be longer than 128 bytes".  Cosa sto sbagliando?

Se altri hanno lo stesso problema, ho trovato un workaround per trovare la chiave senza usare il sito:

- Aprire la pagina del reader con i DevTools e aspettare il caricamento dei contenuti
- Sul tab console dare il comando `window.angularComponentRef.render.settings.encResource` e premere invio. Quella ottenuta è la chiave da utilizzare nel primo input dello script

**Comment by Leone25** [comment]
@GioIacca9 ho provato come dici te e mi funziona, sei sicuro di aver escluso le virgolette?

**Comment by GioIacca9** [comment]
Si, se vuoi provare queste sono le due stringhe:

downloadBook:

```
MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBALboTHUtVNFKi1JWniNjsGGcPhU9Rz8iGCJmdSxPhHexAvfWSlWS7aWJDsA02Wntfs/uZiqMJ7zPiJFMAiEhex0yZMqAAsdMrvIJG53G+3MeDcobrgNx22KRggtkcRf7nS1QWvgZJwbl7q+APB+KA8KXuvvyp5s0npzw/hpJuSQnAgMBAAECgYEAggikUqnnouNcKS1rP72fp8VsXa0y+a9DeTFeHCJsCqvNcGToc+4BBa5qzjrEVoqBnVHfUGBT3+erL6DZ4rPq0aLrpQ78RAMFOnhDKtrXrdFLw8HOxRnW99GLuM+PxWPu4goiAheE73ndatFj1x8yD4WxcNl7kZwM340R6In6gAECQQDj1mfVaT5oXecGYsdcYoghCTeC5XSPrePaChpoKM0Q6fMB2agukHpngILCL2/ExjQMhhpEd7PonJyMQrToDI4HAkEAzYQkzkjnIzX62T2RVBPyf93GkPIDwmAJCyQxL+1zxot1bAV2/CHDW4vdAz5l6FrWrU+op0MB5HSpvtV5n7kw4QJACj7C7orL/p9yWwwoENRxcKLcdytgQXG9VDmuFE75YbBTeBrUgDuI9YyG1LqTWRLclk+VcMy9L1GTjI8XWXPvEwJBALAtSLQB8QrROnJCgjPWSbrtbkxQ+4IEe5wucXAJmYcphAaPBLoNY4A1/MfMFOZEAOZfdE+2dIfYrq8mJ3YR9mECQQC1zqlWSyTNmKT6wo0T4S2wKIKedwXLgcpTCcBKlMeQWpyi1mvE7AQpeUVXKL4SmZreScFwCFx2FpK//bNkmUX3
```

enc_resource.key:
```
T1NIUWk2TWV5RmhnWExLL3U5cEhJZ1VvcFE5bjFPY3laQ0xKbVI0czAwWGZncGIybGtLQ2RzWWVhNDVjMXF6dWUxUjAwb2JTbFZxeHM4MFh3R1dxMmlUR1A0L3QxUnFZeE1Wcll4RFVxTDJkY2pPZVVHbXNGb005eVcra1d2VFMwS21xOG43ZVZPL1UvTGd6U0s2VVJkK0YyY21YQUhHcW05YUc1enVwNFdnPQ==
```

**Comment by Leone25** [comment]
Hmmmm interessante, aggiornerò le istruzioni con il tuo metodo che tbh è migliore...

**Comment by GioIacca9** [comment]
Apprezzo, grazie
