### ISSUE TITLE
window.angularComponentRef.render.settings.encResource undefined

### ISSUE THREAD

**Issue by OnePewPew** [Leone25/kitaboo-downloader#26]
Quando inserisco `window.angularComponentRef.render.settings.encResource` nella console, non appare alcuna stringa, bensì `undefined`

**Comment by Leone25** [comment]
prova a seguire queste istruzioni per ottenere la chiave di criptazione  https://github.com/Leone25/kitaboo-downloader/blob/4c80dd13ce61a1847f93a72178aabbf7767f75d1/README.md

**Comment by LucioAve** [comment]
i try, block on "enc_resource.key" not find

**Comment by Leone25** [comment]
vi siete assicurati che la pagina fosse completamente caricata prima di provare?
Se comunque non c'è, provate a ricaricare la pagina e aspettate di nuovo che sia completamente carica

**Comment by LucioAve** [comment]
niente da fare "enc_resource.key" non esce, mentre "downloadBook", si

**Comment by MatHeartGaming** [comment]
Sto avendo anche io lo stesso problema.

![window angular_undefined](https://github.com/Leone25/kitaboo-downloader/assets/25991137/0e57c439-8bd7-4643-a32f-0e930e700679)

Spero di non aver sbagliato il procedimento. Eseguo `window.angularComponentRef.render.settings.encResource` nella console della pagina del libro, per esempio: [Artelogia](window.angularComponentRef.render.settings.encResource). Sto facendo bene?

**Comment by Leone25** [comment]
puoi cercare perfavore uno dei file che finisce con .svgz nella pagina di rete, cliccaci sopra, vai nella risposta e guarda se inizia con `<?xml version="1.0" encoding="UTF-8"?><svg...` o una serie di lettere e numeri a caso

**Comment by MatHeartGaming** [comment]
Non mi mostra la risposta, purtroppo.

![risposta](https://github.com/Leone25/kitaboo-downloader/assets/25991137/ef7808a2-9e38-4dfd-a0c7-bd664c59501a)

**Comment by Leone25** [comment]
prova con dei file più recenti (in basso), spesso i browser eliminano dalla memoria i dati delle vecchie richieste

**Comment by LucioAve** [comment]
> Sto avendo anche io lo stesso problema.
> 
> ![window angular_undefined](https://user-images.githubusercontent.com/25991137/270181109-0e57c439-8bd7-4643-a32f-0e930e700679.png)
> 
> Spero di non aver sbagliato il procedimento. Eseguo `window.angularComponentRef.render.settings.encResource` nella console della pagina del libro, per esempio: [Artelogia](https://webreader.zanichelli.it/6.0/zanichelli/#/reader?mode=online) Sto facendo bene?

non è lo stesso problema, tu stai seguendo l'altra guida. Io questa:
https://github.com/Leone25/kitaboo-downloader/blob/4c80dd13ce61a1847f93a72178aabbf7767f75d1/README.md

**Comment by LucioAve** [comment]
Leone come posso contattarti direttamente?

**Comment by LucioAve** [comment]
scusatemi, confermo la procedura presente qui:
funziona.
Grazie.

**Comment by LucioAve** [comment]
:( ha funzionato solo 1 volta

**Comment by Leone25** [comment]
> Leone come posso contattarti direttamente?

twitter è il modo migliore, stesso tag + 03

**Comment by OnePewPew** [comment]
Confermo che la ricerca `enc_resource.key` non dà alcun risultato nella scheda network

**Comment by Leone25** [comment]
Perfavore contattami in privato su Twitter

**Comment by Leone25** [comment]
Per le persone che hanno riscontrato il problema del valore indefinito della chiave di criptazione, è stato effettuato un ennesimo aggiornamento con nuove istruzioni.
