### ISSUE TITLE
Error: invalid initialation vector size "index.js"

### ISSUE THREAD

**Issue by samuelemazzeo** [Leone25/kitaboo-downloader#27]
Processing...
Downloading page0001
C:\Users\Samuele\Desktop\kitaboo-downloader-main\node_modules\aes-js\index.js:439
            throw new Error('invalid initialation vector size (must be 16 bytes)');
                  ^

Error: invalid initialation vector size (must be 16 bytes)
    at new ModeOfOperationCBC (C:\Users\Samuele\Desktop\kitaboo-downloader-main\node_modules\aes-js\index.js:439:19)
    at decryptFile (file:///C:/Users/Samuele/Desktop/kitaboo-downloader-main/index.js:16:17)
    at file:///C:/Users/Samuele/Desktop/kitaboo-downloader-main/index.js:75:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Samuele/Desktop/kitaboo-downloader-main/index.js:79:11

Node.js v18.18.0

**Comment by samuelemazzeo** [comment]
Ho riscontrato questo problema, qualcuno riuscirebbe ad aiutarmi a capire come risolverlo?

**Comment by Leone25** [comment]
curioso, potrei vedere la password di cryptazione che hai recuperato?

**Comment by nicola6th** [comment]
Innanzitutto ti ringrazio tantissimo per il tool che hai realizzato.
Ho riscontrato anche io questo errore in un libro con pagine non criptate (il comando "window.angularComponentRef.render.settings.encResource" fornisce come risultato "undefined")

**Comment by nicola6th** [comment]
Anche io avevo un errore simile, ma ho risolto scaricando l'ultima versione del tool.
PS Grazie mille Leone25 per questo preziosissimo tool
