### ISSUE TITLE
Cant copy link when right clicking

### ISSUE THREAD

**Issue by k3v1nwrld** [Leone25/kitaboo-downloader#28]
Hope im not doing anything wrong, heres a screenshot:
![image](https://github.com/Leone25/kitaboo-downloader/assets/75213647/f81f33bd-346a-40b6-8aa8-e138b30d43a4)

**Comment by Leone25** [comment]
they might have changed something, just press the link normally, then open the dev tools and make sure caching is disabled, then reload the page
