### ISSUE TITLE
Problem with Cookies:

### ISSUE THREAD

**Issue by mmatarrese** [Leone25/kitaboo-downloader#29]
Hello! Thank you for your fantastic job. I am trying to follow your guide. I am having problems with item 10. Where exactly should I find this Cookies url to copy? I am using Google chrome browser. I also tried Firefox but I couldn't find any of the codes you were talking. So I would prefer to move on with Chrome.

**Comment by Leone25** [comment]
Here, I hope these screenshots can help

![immagine](https://github.com/Leone25/kitaboo-downloader/assets/39310565/b48cff2a-d560-4338-befe-73cee77509c7)
You have to scroll down in the right bottom panel
![immagine](https://github.com/Leone25/kitaboo-downloader/assets/39310565/2389df14-697d-401d-9d97-2e8c3f510196)

**Comment by mmatarrese** [comment]
Yes, they do! It turned out that AdBlock was causing the "Request Headers" tab to be missing. AdBlock would reactivate everytime upon refreshing the page. Additionally, there were times when content.opf wouldn't appear. I discovered that pressing Ctrl+R solves this issue. Maybe these tips help. Thank you so much for this amazing tool! All my best.
