### ISSUE TITLE
cannot find Cookie

### ISSUE THREAD

**Issue by cicco98** [Leone25/kitaboo-downloader#33]
Hello, everyone,
I followed the guide up to step 9, but in step 10 I don't know where to find the Cookie value. Within the content.opf file there is no cookie and neither in the list of files within the network section. Can anyone help me?

**Comment by cicco98** [comment]
> Could you please share a screenshot showing what you see when you can't find the cookie?

thank you for helping

![Immagine 2024-04-05 140801](https://github.com/Leone25/kitaboo-downloader/assets/166123845/d7736e63-895c-4dc9-950a-9d3753065099)

**Comment by Leone25** [comment]
You have to scroll down in the bottom right panel, there is more info below where it says "intestazioni delle richieste", the cookie should be there
