### ISSUE TITLE
non riesco a trovare il file 'downloadBook'

### ISSUE THREAD

**Issue by pietroaceto-04** [Leone25/kitaboo-downloader#39]
non sono per niente esperto di informatica quindi non so se lo sto cercando nel modo giusto, credo che mi manchi solo la privateKey ma anche smanettando in giro non sono riuscito a trovare nulla, potete aiutarmi?
![Screenshot 2024-07-03 180549](https://github.com/Leone25/kitaboo-downloader/assets/146483078/e01ae90f-ef59-4871-9183-1300f66c4973)

**Comment by mangialorenzo** [comment]
Io ci ho provato qualche giorno fa e riuscivo a trovare il file "downloadBook"... oggi ci ho riprovato e non riesco più a trovarlo...

**Comment by pietroaceto-04** [comment]
quindi almeno per ora non c’è soluzione?

**Comment by Leone25** [comment]
vedo che quelli di zanichelli ci stanno monitorando lol

comunque la soluzione è abbastanza facile:
- Per chrome (e derivati), selezionare la scheda "Application"
- Per firefox, selezionare la scheda "Storage"
Poi dal menu di sinistra espandere "Session Storage", e selezionare `https://webreader.zanichelli.it/`, nella lista dovete cercare la chiave `kek` ed il valore è quello che dovete inserire come chiave privata
