### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'pagination')

### ISSUE THREAD

**Issue by simonc999** [Leone25/kitaboo-downloader#41]
![Immagine 2024-07-10 113314](https://github.com/Leone25/kitaboo-downloader/assets/140884524/8614575d-c946-4df2-b667-226cb0ef1837)

Node.js v21.7.2
I hope that is possible to fix this... Thanks for your work!

**Comment by Leone25** [comment]
curious, could you try logging the response variable right before line 118?

**Comment by simonc999** [comment]
Yes, it says  { message: 'Fatal error: User group not allowed' }

**Comment by simonc999** [comment]
I saw a lot of users insert cookies and other stuff, but the script only asked me for my email and my password, it is correct?

**Comment by Leone25** [comment]
there's been a recent update that simplified the whole process, so yes it is correct indeed.

The error you are getting is definitely curious... would you mind sending me a dm on twitter (same name + 03)

**Comment by simonc999** [comment]
ok sent
