### ISSUE TITLE
Errore Rendering

### ISSUE THREAD

**Issue by NioBee** [Leone25/kitaboo-downloader#5]
Buongiorno,
intanto grazie mille per aver creato questo tool a mio avviso utilissimo!!
Stavo cercando di fare il download di un testo dal sito Z. tuttavia il file che mi ritrovo al termine della procedura è completamente bianco.
Nella finestra CMD tutto fila liscio fino alla parte in cui definisco un nome per il file, poi inizia il download delle singole pagine, ma in ognuna esce il seguente errore:
`SVGtoPDF: this element can't be rendered directly: Error
Downloading 678/678
SVGtoPDF: this element can't be rendered directly: Error
Done! You'll find the PDF in the directory of the script
PS C:\kitaboo-downloader-main>`

Avevo avuto lo stesso problema anche su altro PC, pensando fosse in qualche modo legato alla macchina un po' vecchiotta e non più performante, ho provato dal mio notebook, ma il risultato è lo stesso.. dove sbaglio?

Grazie. Patrizia

Informazioni di sistema: 
Windows 10 Home a 64 bit
8gb di Ram
Intel i5-7200U
Node LTS Version: 16.13.0 installata da amministratore attivando lo script

**Comment by Leone25** [comment]
Buongiorno,
sono contento che le sia stato utile il mio programma!
L'errore che riceve lei sono 99/100 sicuro che sia dovuto a qualche errore nell'inserimento dei dati, in particolare dei cookie. Faccia riferimento a quest'altra issue https://github.com/Leone25/kitaboo-downloader/issues/3 e se non risolve mi contatti su twitter in privato così posso darle una mano senza esporre dati, mi chiamo come su github+03

Mi faccia sapere

Enrico

**Comment by NioBee** [comment]
Grazie mille, effettivamente anche se il cookie era bello lungo e complesso, aveva i "famosi" tre puntini al suo interno.. ora l'ho ricopiato e sembra funzionare correttamente.. attendo la fine della procedura, ma sono certa che adesso non avrò problemi! 👍

**Comment by Leone25** [comment]
Nessun problema, è qualcosa di comune e dovre decidermi di implementare qualcosa per avvisare l'utente.

Buona giornata
