### ISSUE TITLE
Errore nell'inserimento dell'url.

### ISSUE THREAD

**Issue by Simsiano** [Leone25/kitaboo-downloader#7]
Una volta inserito l'url sul cmd viene mostrato questo errore:

Processing...
Error:  TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\Desktop\kitaboo-downloader-main\node_modules\node-fetch\lib\index.js:1327:9)
    at C:\Users\Desktop\kitaboo-downloader-main\node_modules\node-fetch\lib\index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\Desktop\kitaboo-downloader-main\node_modules\node-fetch\lib\index.js:1437:9)
    at C:\Users\Desktop\kitaboo-downloader-main\index.js:21:27
    at Object.<anonymous> (C:\Users\Desktop\kitaboo-downloader-main\index.js:97:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)

P.S.: Nome utente rimosso dall'indirizzo.

**Comment by Leone25** [comment]
Sembra che tu abbia incollato l'url nel modo sbagliato

Mi potresti mostrare ciò che hai incollato

**Comment by Simsiano** [comment]
Ho incollato questo link.
L'ho trovato clicclanto su "risorse" e poi ho fatto tasto destro su "leggi il libro online".
Il link è questo:
https://web-booktab.zanichelli.it/?idOpera=1273084B6BDF2F83C1257B86004FE5FF

**Comment by Simsiano** [comment]
Notando bene quando incollo il link sul cmd, quello che incolla è questo:

C:\Users\Valerio\Desktop\kitaboo-downloader-main>node .
Input the url: httpts/t/e/bb
Input the url: httpts/t/e/bb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
Input the url: httpts/t/e/bb
okstb
.a?nc.hlbl./i/l?d?Oenr=?17Q38b46rBF?28
31h27oB6B04bF5tF


E' normale?

**Comment by Leone25** [comment]
direi di no . . . 

cioè è normale che si ripeta varie volte per un bug nella libreria, ma non è normale il link sia così.
un esempio di link valido: `https://my.zanichelli.it/kitaboo/2db34b2b19ce0f0bcec829b7f3697631` (valido solo per un tot di tempo)
tra l'altro il libro sembra essere di booktab, è una piattaforma separata e c'è un link per uno script diverso sul readme

la differenza fondamentale è che kitaboo ha il dominio `webreader.zanichelli.it` e booktab ha il dominio `web-booktab.zanichelli.it` quando si apre il libro

**Comment by Simsiano** [comment]
Ah ecco perché. Io ho comunque provato ad usare l'altro script su python ma mi dice che il modulo PyPDF2 non è presente. Inoltre l'istallazione dei requisiti mi dà in errore.

**Comment by Leone25** [comment]
usa il comando `pip install requests PyPDF2` ed ignora il primo passaggio (per booktab)
