### ISSUE TITLE
errore durante creazione PDF

### ISSUE THREAD

**Issue by dani9099** [Leone25/kitaboo-downloader#8]
ciao, innanzitutto grazie mille per questo tool! E' esattamente quello che stavo cercando

dopo l'inserimento dell' URL ho ottenuto questo errore:

Input the url: https://my.zanichelli.it/kitaboo/984183186282991c279f6103f409a150
Processing...
Error:  Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: E
---------

 utilizzando ispeziona elemento ho notato che lo schema dell' URL che punta al file "content.opf" è cambiato (mi riferisco all'URL di "let content" del file index.js).. l'ho corretto quindi nello schema aggiornato "let content = await fetch(`https://webreader.zanichelli.it/ContentServer/mvc/s3view/${ebookID}/fixed_epub_image/${ebookID}/OEBPS/content.opf`"

ho rieseguito lo script reinserendo stesso URL "https://my.zanichelli.it/kitaboo/984183186282991c279f6103f409a150"
ottenedo un file pdf con pagine  vuote e ciò che segue..

Input the url: https://my.zanichelli.it/kitaboo/984183186282991c279f6103f409a150
Processing...
Downloading Frontespizio.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Dichiaratoria.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading PrefazioneItaliana.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Revisori.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Prefazione.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Autori.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading EditorVE.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Indice.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte01.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte02.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte03.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte04.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte05.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte06.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte07.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte08.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte09.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte10.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte11.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte12.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte13.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte14.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte15.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte16.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte17.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte18.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte19.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte20.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte21.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte22.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte23.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Parte24.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Downloading Crediti.xhtml
parseXml: data after document end has been discarded
SVGtoPDF: the input does not look like a valid SVG
Done! You'll find the PDF in the directory of the script

ho notato che non stanno utilizzando più il formato SVG (perlomeno nel mio libro in questione).. ma purtroppo non ho competenze sufficienti per modificare ad hoc la parte rimanente dello script!

allego il file "content.opf" in xml
[content.xml.zip](https://github.com/Leone25/kitaboo-downloader/files/9859129/content.xml.zip)

grazie in anticipo

**Comment by Leone25** [comment]
Grazie, gli darò uno sguardo, purtroppo zanichelli usa mille milioni di formati diversi che sono un casino da gestire, quindi devo vedere ciò che posso fare. Ti informerò quando ho più notizie

**Comment by dani9099** [comment]
figurati immaginavo!
Grazie ancora, mi sarebbe utilissimo avere il PDF a portata di mano dato che il loro sito è abbastanza penoso.
Comunque il libro in questione è molto complesso.. fai come riesci .. se avessi bisogno del link kitaboo aggiornato te lo rimando subito

P.S: avevo modificato analogamente anche lo schema dell' URL di "const svg".. ma il risultato è lo stesso

**Comment by Leone25** [comment]
Ok, ho appena guardato e purtroppo ciò che stanno facendo è usare html al posto di svg, dovrei scrivere un convertitore, ma non posso adesso, non sei il primo che ha questo problema. Se vuoi puoi provare ad usare questo script https://github.com/FelixFrog/pdfgrabber , io non l'ho provato ma sostiene di poter fare la conversione.

**Comment by dani9099** [comment]
appena provato https://github.com/FelixFrog/pdfgrabber purtroppo non si riesce neanche li, grazie mille lo stesso!
